bz: don't assume message has an event in subtitle processing
This seems to be causing datagrepper to choke on some message(s)
from early 2018 - this search:
https://apps.fedoraproject.org/datagrepper/raw?start=1518556860&end=1518556935
produces a traceback that ends:

line 106, in subtitle
    if 'bug.new' in msg['topic'] or (msg['msg']['event'].get('target') == 'bug' and
AttributeError: 'NoneType' object has no attribute 'get'

Several other places in the code protect against a message not
having an event, so it seems logical to also do so here.

Signed-off-by: Adam Williamson <awilliam@redhat.com>